-- I CREATED A DATABASE HERE
CREATE database JULYCOHORT_DB;

USE JULYCOHORT_DB;

-- CREATING A TABLE
CREATE TABLE STUDENTS_TB (
ID_STND INT(13),
STND_NAME varchar(30),
AGE INT(4),
GENDER VARCHAR(10),
COURSE VARCHAR(20) );

USE JULYCOHORT_DB;

-- NEW TABLE 20/08/2023
CREATE TABLE JULY_CLASS_TB (
CLASS_ID INT(11),
CLASS_NAME VARCHAR(40),
CLASS_COURSE VARCHAR(20),
PRIMARY KEY (CLASS_ID) );


CREATE TABLE COURSE_TB (
COURSE_ID VARCHAR(10),
COURSE_LECT VARCHAR(20),
CLASS_ID INT(11),
PRIMARY KEY (COURSE_ID) );


/* INSERTING DATA INTO MY TABLE METHOD 1
INSERT INTO table_name (column1, column2, column3, ......)
VALUES(value1, value2, value3, ......)*/

/* INSERTING DATA INTO MY TABLE METHOD 2
INSERT INTO table_name VALUES(values1, values2, values3, ....) */

INSERT INTO JULY_CLASS_TB VALUES ( 1, 'JULY 2023', 'DATA ANALYTICS');
INSERT INTO JULY_CLASS_TB VALUES ( 2, 'JULY 2023', 'BUSINESS ANALYTICS');
INSERT INTO JULY_CLASS_TB VALUES ( 3, 'JULY 2023', 'MACHINE LEARNING');

/* QUERY JULY_CLASS_TB METHOD 1
SELECT column1, column2, column3, ......  FROM table_name*/
SELECT CLASS_ID, CLASS_NAME, CLASS_COURSE FROM JULY_CLASS_TB;

/* QUERY JULY_CLASS_TB METHOD 2
SELECT *  FROM table_name*/

* = ALL

SELECT * FROM JULY_CLASS_TB;

* QUERY JULY_CLASS_TB METHOD 1
SELECT column1, column2, column3, ......  FROM table_name*/
SELECT CLASS_ID, CLASS_NAME, CLASS_COURSE FROM JULY_CLASS_TB;

/* QUERY JULY_CLASS_TB METHOD 2
SELECT *  FROM table_name*/
* = ALL
SELECT * FROM JULY_CLASS_TB;

/* UPDATING JULY_CLASS_TB METHOD 1*
UPDATE table_name
SET column1 = value1
WHERE condition 
*/

-- SET SQL_SAFE_UPDATES =0;
-- UPDATING JULY_CLASS_TB METHOD 1
UPDATE JULY_CLASS_TB
SET CLASS_COURSE= 'CODING'
WHERE CLASS_ID= 3;

/* DELETING FROM JULY_CLASS_TB
	DELETE FROM table_name WHERE condition
*/

DELETE FROM 

